In [1]:
# # configs
# import tomllib
# from pathlib import Path
# with open(Path.cwd() / "configs.toml", "rb") as config_file:
#     notebook_config = tomllib.load(config_file)
#
# config_path = notebook_config["configs"]["location"]
#
# with open(config_path, "rb") as f:
#     configs = tomllib.load(f)
#
# print(f"Metadata at: {configs['dataset']['metadata']}")
# print(f"Images at: {configs['dataset']['images']}")
# print(f"Annotations at: {configs['dataset']['annotations']}")

from utility.paths import PathList

print(f"Images at: {PathList.raw_luna_image_dir}")
print(f"Annotations at: {PathList.raw_luna_annotation_csv}")

Images at: /Users/muang/Edinburgh/Diss/lung-tumour/data/LUNA/raw/image
Annotations at: /Users/muang/Edinburgh/Diss/lung-tumour/data/LUNA/raw/annotation/LUNA25_Public_Training_Development_Data.csv

In [2]:
# annotations
import pandas as pd

annotations_pd = pd.read_csv(PathList.raw_luna_annotation_csv)
annotations_pd.head()

,PatientID,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
0,100570,1.2.840.113654.2.55.32380467633296345717423514...,19990102,61.14,-163.28,-177.75,1,100570_1_19990102,100570_1,1,63,Male
1,106364,1.2.840.113654.2.55.16930993607533226779708566...,19990102,30.64,-95.96,-128.59,1,106364_1_19990102,106364_1,1,67,Female
2,127302,1.2.840.113654.2.55.13728437630416839550344528...,20000102,-82.53,-27.85,-209.46,1,127302_1_20000102,127302_1,1,61,Male
3,128899,1.2.840.113654.2.55.40415300708683206534849072...,20010102,-38.69,-8.78,-39.43,1,128899_1_20010102,128899_1,1,64,Male
4,215816,1.3.6.1.4.1.14519.5.2.1.7009.9004.241362276021...,19990102,32.89,-37.98,-100.04,1,215816_1_19990102,215816_1,1,69,Female

In [3]:
# number of patients
annotations_pd.groupby("PatientID").size()

PatientID
100012     2
100035     3
100069     6
100095    12
100150     2
          ..
218781     1
218817     1
218829     3
218863     2
218866     1
Length: 2120, dtype: int64

In [4]:
annotations_pd

,PatientID,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
0,100570,1.2.840.113654.2.55.32380467633296345717423514...,19990102,61.14,-163.28,-177.75,1,100570_1_19990102,100570_1,1,63,Male
1,106364,1.2.840.113654.2.55.16930993607533226779708566...,19990102,30.64,-95.96,-128.59,1,106364_1_19990102,106364_1,1,67,Female
2,127302,1.2.840.113654.2.55.13728437630416839550344528...,20000102,-82.53,-27.85,-209.46,1,127302_1_20000102,127302_1,1,61,Male
3,128899,1.2.840.113654.2.55.40415300708683206534849072...,20010102,-38.69,-8.78,-39.43,1,128899_1_20010102,128899_1,1,64,Male
4,215816,1.3.6.1.4.1.14519.5.2.1.7009.9004.241362276021...,19990102,32.89,-37.98,-100.04,1,215816_1_19990102,215816_1,1,69,Female
...,...,...,...,...,...,...,...,...,...,...,...,...
6158,123244,1.2.840.113654.2.55.96785330641884045479008848...,20010102,50.88,55.09,1816.38,1,123244_1_20010102,123244_1,0,73,Female
6159,104196,1.2.840.113654.2.55.67476228289351741200494264...,20000102,84.01,-94.42,1106.82,1,104196_1_20000102,104196_1,0,58,Female
6160,104196,1.2.840.113654.2.55.24806580836056963319112187...,20010102,70.29,-85.76,1904.06,1,104196_1_20010102,104196_1,0,59,Female
6161,204005,1.3.6.1.4.1.14519.5.2.1.7009.9004.291214500058...,19990102,128.81,11.64,-256.59,1,204005_1_19990102,204005_1,0,59,Male
6162,204005,1.3.6.1.4.1.14519.5.2.1.7009.9004.204863242782...,20000102,128.80,-3.87,-248.66,1,204005_1_20000102,204005_1,0,60,Male

In [5]:
# patient label the same or not
annotations_pd.groupby("PatientID")["label"].nunique().sort_values()

PatientID
100012    1
134616    1
134612    1
134593    1
134558    1
         ..
117751    1
117737    1
117699    1
117950    1
218866    1
Name: label, Length: 2120, dtype: int64

In [6]:
|# number of benign nodules
annotations_pd[annotations_pd["label"] == 0]

SyntaxError: invalid syntax (3044889236.py, line 1)

In [7]:
annotations_pd[annotations_pd["label"] == 1]

,PatientID,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
0,100570,1.2.840.113654.2.55.32380467633296345717423514...,19990102,61.140000,-163.280000,-177.750000,1,100570_1_19990102,100570_1,1,63,Male
1,106364,1.2.840.113654.2.55.16930993607533226779708566...,19990102,30.640000,-95.960000,-128.590000,1,106364_1_19990102,106364_1,1,67,Female
2,127302,1.2.840.113654.2.55.13728437630416839550344528...,20000102,-82.530000,-27.850000,-209.460000,1,127302_1_20000102,127302_1,1,61,Male
3,128899,1.2.840.113654.2.55.40415300708683206534849072...,20010102,-38.690000,-8.780000,-39.430000,1,128899_1_20010102,128899_1,1,64,Male
4,215816,1.3.6.1.4.1.14519.5.2.1.7009.9004.241362276021...,19990102,32.890000,-37.980000,-100.040000,1,215816_1_19990102,215816_1,1,69,Female
...,...,...,...,...,...,...,...,...,...,...,...,...
5056,134257,1.2.840.113654.2.55.19134143636557242072696988...,20000102,-70.240000,-88.790000,-106.560000,1,134257_1_20000102,134257_1,1,57,Female
5057,121794,1.2.840.113654.2.55.12380093464274311544899469...,19990102,-83.950000,0.250000,-7.900000,1,121794_1_19990102,121794_1,1,61,Female
5058,124323,1.2.840.113654.2.55.98593203147463241270004148...,19990102,-26.096359,27.702484,-112.619995,1,124323_1_19990102,124323_1,1,68,Female
5059,124323,1.2.840.113654.2.55.15295642153836765678497653...,20000102,-28.832626,11.085663,-140.695007,1,124323_1_20000102,124323_1,1,69,Female
5060,124323,1.2.840.113654.2.55.16466886792267601226886887...,20010102,-30.280000,34.530000,-91.120000,1,124323_1_20010102,124323_1,1,70,Female

In [8]:
# patient level
patients_first_rows = annotations_pd.groupby("PatientID").first()

In [9]:
patients_first_rows[patients_first_rows["label"] == 0]

,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
PatientID,,,,,,,,,,,
100035,1.2.840.113654.2.55.64360087057061878755830205...,19990102,124.67,5.85,-193.59,1,100035_1_19990102,100035_1,0,55,Female
100069,1.2.840.113654.2.55.31894721532710462657515245...,20000102,-65.34,-33.52,1520.24,1,100069_1_20000102,100069_1,0,65,Female
100095,1.2.840.113654.2.55.22461859041957100493421265...,19990102,-103.37,9.98,-1055.80,3,100095_3_19990102,100095_3,0,64,Male
100150,1.2.840.113654.2.55.20992147629817300553457726...,20000102,108.03,-234.40,-242.26,1,100150_1_20000102,100150_1,0,57,Male
100151,1.2.840.113654.2.55.20488740121532740427073763...,19990102,-102.89,-254.79,-218.46,1,100151_1_19990102,100151_1,0,61,Male
...,...,...,...,...,...,...,...,...,...,...,...
218781,1.3.6.1.4.1.14519.5.2.1.7009.9004.784923545329...,20010102,24.89,-145.18,-84.92,1,218781_1_20010102,218781_1,0,63,Male
218817,1.3.6.1.4.1.14519.5.2.1.7009.9004.309396145578...,20010102,-53.35,-1.23,1701.81,1,218817_1_20010102,218817_1,0,62,Male
218829,1.3.6.1.4.1.14519.5.2.1.7009.9004.173225373237...,19990102,-131.36,-190.63,-205.68,1,218829_1_19990102,218829_1,0,59,Female
218863,1.3.6.1.4.1.14519.5.2.1.7009.9004.977896926234...,19990102,69.72,-48.07,-86.47,2,218863_2_19990102,218863_2,0,62,Female
218866,1.3.6.1.4.1.14519.5.2.1.7009.9004.698887010763...,20000102,31.26,-216.76,250.57,1,218866_1_20000102,218866_1,0,58,Male

In [10]:
patients_first_rows[patients_first_rows["label"] == 1]

,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
PatientID,,,,,,,,,,,
100012,1.2.840.113654.2.55.24023112856488152536348979...,19990102,-32.919853,-136.221390,-90.400002,1,100012_1_19990102,100012_1,1,61,Female
100560,1.2.840.113654.2.55.17578653928177999534065174...,19990102,67.450000,47.320000,-160.590000,1,100560_1_19990102,100560_1,1,64,Male
100570,1.2.840.113654.2.55.32380467633296345717423514...,19990102,61.140000,-163.280000,-177.750000,1,100570_1_19990102,100570_1,1,63,Male
100619,1.2.840.113654.2.55.29428177947056655991969749...,19990102,-64.780000,64.500000,-52.460000,1,100619_1_19990102,100619_1,1,68,Male
100703,1.2.840.113654.2.55.25529804576667997729629261...,19990102,-103.340000,14.150000,-97.270000,1,100703_1_19990102,100703_1,1,62,Male
...,...,...,...,...,...,...,...,...,...,...,...
217756,1.3.6.1.4.1.14519.5.2.1.7009.9004.210391197267...,20000102,102.550000,55.300000,-84.190000,1,217756_1_20000102,217756_1,1,75,Male
217862,1.3.6.1.4.1.14519.5.2.1.7009.9004.196319339638...,19990102,-96.760000,-165.340000,-142.380000,1,217862_1_19990102,217862_1,1,59,Male
218035,1.3.6.1.4.1.14519.5.2.1.7009.9004.138565929432...,19990102,-58.274139,19.171127,1493.000000,1,218035_1_19990102,218035_1,1,65,Male
218391,1.3.6.1.4.1.14519.5.2.1.7009.9004.163866305568...,19990102,-47.242271,28.389816,-52.850006,1,218391_1_19990102,218391_1,1,66,Male
218499,1.3.6.1.4.1.14519.5.2.1.7009.9004.174968770387...,19990102,-83.947380,-16.758804,-71.674988,1,218499_1_19990102,218499_1,1,63,Male

In [11]:
# Secondary characteristics
# males?
males = patients_first_rows[patients_first_rows["Gender"] == "Male"]
males

,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
PatientID,,,,,,,,,,,
100095,1.2.840.113654.2.55.22461859041957100493421265...,19990102,-103.37,9.98,-1055.80,3,100095_3_19990102,100095_3,0,64,Male
100150,1.2.840.113654.2.55.20992147629817300553457726...,20000102,108.03,-234.40,-242.26,1,100150_1_20000102,100150_1,0,57,Male
100151,1.2.840.113654.2.55.20488740121532740427073763...,19990102,-102.89,-254.79,-218.46,1,100151_1_19990102,100151_1,0,61,Male
100285,1.2.840.113654.2.55.14354832218744395267379933...,19990102,-76.97,89.64,-190.51,1,100285_1_19990102,100285_1,0,71,Male
100289,1.2.840.113654.2.55.14142391905329120814972777...,20010102,-50.31,-124.86,-52.75,4,100289_4_20010102,100289_4,0,57,Male
...,...,...,...,...,...,...,...,...,...,...,...
218698,1.3.6.1.4.1.14519.5.2.1.7009.9004.296957636483...,19990102,120.31,62.84,-1417.41,1,218698_1_19990102,218698_1,0,57,Male
218727,1.3.6.1.4.1.14519.5.2.1.7009.9004.317304888254...,20000102,137.84,-224.88,92.67,1,218727_1_20000102,218727_1,0,75,Male
218781,1.3.6.1.4.1.14519.5.2.1.7009.9004.784923545329...,20010102,24.89,-145.18,-84.92,1,218781_1_20010102,218781_1,0,63,Male
218817,1.3.6.1.4.1.14519.5.2.1.7009.9004.309396145578...,20010102,-53.35,-1.23,1701.81,1,218817_1_20010102,218817_1,0,62,Male
218866,1.3.6.1.4.1.14519.5.2.1.7009.9004.698887010763...,20000102,31.26,-216.76,250.57,1,218866_1_20000102,218866_1,0,58,Male

In [12]:
males[males["label"] == 0]

,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
PatientID,,,,,,,,,,,
100095,1.2.840.113654.2.55.22461859041957100493421265...,19990102,-103.37,9.98,-1055.80,3,100095_3_19990102,100095_3,0,64,Male
100150,1.2.840.113654.2.55.20992147629817300553457726...,20000102,108.03,-234.40,-242.26,1,100150_1_20000102,100150_1,0,57,Male
100151,1.2.840.113654.2.55.20488740121532740427073763...,19990102,-102.89,-254.79,-218.46,1,100151_1_19990102,100151_1,0,61,Male
100285,1.2.840.113654.2.55.14354832218744395267379933...,19990102,-76.97,89.64,-190.51,1,100285_1_19990102,100285_1,0,71,Male
100289,1.2.840.113654.2.55.14142391905329120814972777...,20010102,-50.31,-124.86,-52.75,4,100289_4_20010102,100289_4,0,57,Male
...,...,...,...,...,...,...,...,...,...,...,...
218698,1.3.6.1.4.1.14519.5.2.1.7009.9004.296957636483...,19990102,120.31,62.84,-1417.41,1,218698_1_19990102,218698_1,0,57,Male
218727,1.3.6.1.4.1.14519.5.2.1.7009.9004.317304888254...,20000102,137.84,-224.88,92.67,1,218727_1_20000102,218727_1,0,75,Male
218781,1.3.6.1.4.1.14519.5.2.1.7009.9004.784923545329...,20010102,24.89,-145.18,-84.92,1,218781_1_20010102,218781_1,0,63,Male
218817,1.3.6.1.4.1.14519.5.2.1.7009.9004.309396145578...,20010102,-53.35,-1.23,1701.81,1,218817_1_20010102,218817_1,0,62,Male
218866,1.3.6.1.4.1.14519.5.2.1.7009.9004.698887010763...,20000102,31.26,-216.76,250.57,1,218866_1_20000102,218866_1,0,58,Male

In [13]:
males[males["label"] == 1]

,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
PatientID,,,,,,,,,,,
100560,1.2.840.113654.2.55.17578653928177999534065174...,19990102,67.450000,47.320000,-160.590000,1,100560_1_19990102,100560_1,1,64,Male
100570,1.2.840.113654.2.55.32380467633296345717423514...,19990102,61.140000,-163.280000,-177.750000,1,100570_1_19990102,100570_1,1,63,Male
100619,1.2.840.113654.2.55.29428177947056655991969749...,19990102,-64.780000,64.500000,-52.460000,1,100619_1_19990102,100619_1,1,68,Male
100703,1.2.840.113654.2.55.25529804576667997729629261...,19990102,-103.340000,14.150000,-97.270000,1,100703_1_19990102,100703_1,1,62,Male
100709,1.2.840.113654.2.55.10701638946141874888069138...,19990102,-55.650000,-4.240000,-173.820000,1,100709_1_19990102,100709_1,1,72,Male
...,...,...,...,...,...,...,...,...,...,...,...
217756,1.3.6.1.4.1.14519.5.2.1.7009.9004.210391197267...,20000102,102.550000,55.300000,-84.190000,1,217756_1_20000102,217756_1,1,75,Male
217862,1.3.6.1.4.1.14519.5.2.1.7009.9004.196319339638...,19990102,-96.760000,-165.340000,-142.380000,1,217862_1_19990102,217862_1,1,59,Male
218035,1.3.6.1.4.1.14519.5.2.1.7009.9004.138565929432...,19990102,-58.274139,19.171127,1493.000000,1,218035_1_19990102,218035_1,1,65,Male
218391,1.3.6.1.4.1.14519.5.2.1.7009.9004.163866305568...,19990102,-47.242271,28.389816,-52.850006,1,218391_1_19990102,218391_1,1,66,Male
218499,1.3.6.1.4.1.14519.5.2.1.7009.9004.174968770387...,19990102,-83.947380,-16.758804,-71.674988,1,218499_1_19990102,218499_1,1,63,Male

In [14]:
# females
females = patients_first_rows[patients_first_rows["Gender"] == "Female"]
females

,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
PatientID,,,,,,,,,,,
100012,1.2.840.113654.2.55.24023112856488152536348979...,19990102,-32.919853,-136.22139,-90.400002,1,100012_1_19990102,100012_1,1,61,Female
100035,1.2.840.113654.2.55.64360087057061878755830205...,19990102,124.670000,5.85000,-193.590000,1,100035_1_19990102,100035_1,0,55,Female
100069,1.2.840.113654.2.55.31894721532710462657515245...,20000102,-65.340000,-33.52000,1520.240000,1,100069_1_20000102,100069_1,0,65,Female
100206,1.2.840.113654.2.55.24697903244018314759511100...,20010102,54.880000,-64.63000,-212.560000,1,100206_1_20010102,100206_1,0,59,Female
100282,1.2.840.113654.2.55.31383051098859272812238832...,20010102,-39.820000,-115.02000,-217.490000,5,100282_5_20010102,100282_5,0,66,Female
...,...,...,...,...,...,...,...,...,...,...,...
218521,1.3.6.1.4.1.14519.5.2.1.7009.9004.855211409393...,19990102,-47.800000,-21.18000,-113.390000,1,218521_1_19990102,218521_1,0,69,Female
218685,1.3.6.1.4.1.14519.5.2.1.7009.9004.258728945544...,19990102,107.710000,-16.25000,-161.630000,1,218685_1_19990102,218685_1,0,64,Female
218690,1.3.6.1.4.1.14519.5.2.1.7009.9004.610883885870...,19990102,-101.330000,138.50000,-1498.710000,1,218690_1_19990102,218690_1,0,71,Female
218829,1.3.6.1.4.1.14519.5.2.1.7009.9004.173225373237...,19990102,-131.360000,-190.63000,-205.680000,1,218829_1_19990102,218829_1,0,59,Female
218863,1.3.6.1.4.1.14519.5.2.1.7009.9004.977896926234...,19990102,69.720000,-48.07000,-86.470000,2,218863_2_19990102,218863_2,0,62,Female

In [15]:
females[females["label"] == 0]

,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
PatientID,,,,,,,,,,,
100035,1.2.840.113654.2.55.64360087057061878755830205...,19990102,124.67,5.85,-193.59,1,100035_1_19990102,100035_1,0,55,Female
100069,1.2.840.113654.2.55.31894721532710462657515245...,20000102,-65.34,-33.52,1520.24,1,100069_1_20000102,100069_1,0,65,Female
100206,1.2.840.113654.2.55.24697903244018314759511100...,20010102,54.88,-64.63,-212.56,1,100206_1_20010102,100206_1,0,59,Female
100282,1.2.840.113654.2.55.31383051098859272812238832...,20010102,-39.82,-115.02,-217.49,5,100282_5_20010102,100282_5,0,66,Female
100440,1.2.840.113654.2.55.84727031191603786551242406...,20000102,-71.19,71.62,-66.29,1,100440_1_20000102,100440_1,0,60,Female
...,...,...,...,...,...,...,...,...,...,...,...
218521,1.3.6.1.4.1.14519.5.2.1.7009.9004.855211409393...,19990102,-47.80,-21.18,-113.39,1,218521_1_19990102,218521_1,0,69,Female
218685,1.3.6.1.4.1.14519.5.2.1.7009.9004.258728945544...,19990102,107.71,-16.25,-161.63,1,218685_1_19990102,218685_1,0,64,Female
218690,1.3.6.1.4.1.14519.5.2.1.7009.9004.610883885870...,19990102,-101.33,138.50,-1498.71,1,218690_1_19990102,218690_1,0,71,Female
218829,1.3.6.1.4.1.14519.5.2.1.7009.9004.173225373237...,19990102,-131.36,-190.63,-205.68,1,218829_1_19990102,218829_1,0,59,Female
218863,1.3.6.1.4.1.14519.5.2.1.7009.9004.977896926234...,19990102,69.72,-48.07,-86.47,2,218863_2_19990102,218863_2,0,62,Female

In [16]:
females[females["label"] == 1]

,SeriesInstanceUID,StudyDate,CoordX,CoordY,CoordZ,LesionID,AnnotationID,NoduleID,label,Age_at_StudyDate,Gender
PatientID,,,,,,,,,,,
100012,1.2.840.113654.2.55.24023112856488152536348979...,19990102,-32.919853,-136.22139,-90.400002,1,100012_1_19990102,100012_1,1,61,Female
101287,1.2.840.113654.2.55.21448318257051231937749552...,19990102,4.220000,2.66000,1181.630000,1,101287_1_19990102,101287_1,1,74,Female
101397,1.2.840.113654.2.55.20093274833398222727010571...,19990102,-83.760000,58.33000,-87.310000,1,101397_1_19990102,101397_1,1,59,Female
101834,1.2.840.113654.2.55.98360851027786845429916202...,19990102,-96.000000,-20.88000,-64.690000,1,101834_1_19990102,101834_1,1,68,Female
102658,1.2.840.113654.2.55.21379196846380325247937086...,19990102,60.190842,-180.35115,-45.500000,1,102658_1_19990102,102658_1,1,57,Female
...,...,...,...,...,...,...,...,...,...,...,...
216238,1.3.6.1.4.1.14519.5.2.1.7009.9004.926070962577...,19990102,-83.010000,9.10000,-85.470000,1,216238_1_19990102,216238_1,1,68,Female
216370,1.3.6.1.4.1.14519.5.2.1.7009.9004.189765006180...,19990102,46.190000,33.21000,1629.050000,1,216370_1_19990102,216370_1,1,71,Female
216940,1.3.6.1.4.1.14519.5.2.1.7009.9004.315936508105...,20000102,94.680000,58.13000,-53.850000,1,216940_1_20000102,216940_1,1,62,Female
217465,1.3.6.1.4.1.14519.5.2.1.7009.9004.323969807773...,19990102,-57.660000,-77.47000,-181.700000,1,217465_1_19990102,217465_1,1,65,Female
217482,1.3.6.1.4.1.14519.5.2.1.7009.9004.119783781701...,19990102,94.810000,78.30000,1638.470000,1,217482_1_19990102,217482_1,1,57,Female

In [26]:
from luna_dataset.processing import add_patients_stratifying_key
splitter_pd = add_patients_stratifying_key(annotations_pd.copy())
spd = splitter_pd.groupby("PatientID").nunique()
spd["stratifying_key"].max()

np.int64(1)

In [21]:
# first item
from luna_dataset.utils import pull_data_raw
first_id = annotations_pd["AnnotationID"].iloc[0]
first_npy = pull_data_raw(first_id)
first_npy.shape

(64, 128, 128)